[tool.poetry]
name = "pwn"
version = "0.1.0"
description = "Pwn your coworkers shells"
authors = ["Brian Schiller <brian@devetry.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.1"
jinja2 = "^2.10.3"
